---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Hugo Files
        uses: klakegg/actions-hugo@1.0.0
        env:
          HUGO_DESTINATION: docs

      - name: Commit Blog Changes
        uses: stefanzweifel/git-auto-commit-action@v4
