---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: klakegg/actions-hugo@1.0.0

#  - uses: stefanzweifel/git-auto-commit-action@v4
